name: Terraform AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.8

      - name: Setup Checkov
        run: |
          curl -L https://github.com/bridgecrewio/checkov/releases/latest/download/checkov_linux_amd64 -o checkov
          chmod +x checkov
          sudo mv checkov /usr/local/bin/checkov

      - name: Terraform Init
        working-directory: .
        run: terraform init

      - name: Checkov Test
        working-directory: .
        run: checkov -d .

      - name: Terraform Plan
        working-directory: .
        run: terraform plan

      - name: Terraform Apply
        working-directory: .
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        working-directory: .
        run: terraform destroy -auto-approve
